BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Email] (
    [id] INT NOT NULL IDENTITY(1,1),
    [Marea] NVARCHAR(1000) NOT NULL,
    [Serial] NVARCHAR(1000) NOT NULL,
    [Result] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Email_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Email_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [Email_Marea_key] UNIQUE NONCLUSTERED ([Marea]),
    CONSTRAINT [Email_Serial_key] UNIQUE NONCLUSTERED ([Serial])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
